name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # TFLite
  tflite_flutter: ^0.11.0
  image_picker: ^0.8.7+4

  # Flutter & UI
  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.1

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.1
  firebase_storage: ^13.0.3
  cloud_firestore: ^6.0.3
  file_picker: ^10.3.3
  http: ^1.5.0

  # Other packages
  camera: ^0.11.2
  google_ml_kit: ^0.20.0
  image: ^4.5.4
  printing: ^5.11.2
  pdf: ^3.10.4
  share_plus: ^7.0.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  google_fonts: ^6.0.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background.jpg
    - assets/logo.png
    - assets/seal.png
    - assets/models/facenet.tflite
